// -
// -
// finnonly@outlook.com
// 2026-01-26
// -
// -

namespace Finnonly.Avalonia;

/// <summary>
/// Provider for event binding services.
/// Source generator will register implementations at module initialization.
/// </summary>
public static class EventBindProvider
{
    /// <summary>
    /// Invokes a method on the target object by name with the given parameters.
    /// Implemented by MethodDispatcher generated by source generator.
    /// </summary>
    public static Action<object, string, object?[]>? InvokeMethod { get; set; }

    /// <summary>
    /// Gets the event handler type for a given event on a control type.
    /// Implemented by VEventHelper generated by source generator.
    /// </summary>
    public static Func<Type, string, Type>? GetEventType { get; set; }

    /// <summary>
    /// Creates a delegate of the specified type that wraps the given action.
    /// Implemented by AOTDelegateHelper generated by source generator.
    /// </summary>
    public static Func<Type, Action<object?, object?>, Delegate>? CreateDelegate { get; set; }

    /// <summary>
    /// Whether the provider is initialized with source generator implementations.
    /// </summary>
    public static bool IsInitialized => InvokeMethod != null && GetEventType != null && CreateDelegate != null;
}
